language: python

python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - sudo python setup.py develop

script: sudo python setup.py test

branches:
    only:
        - master

